// Generated by CoffeeScript 1.6.3
(function() {
  var BindingsClass, BindingsInstance;

  BindingsClass = {
    model: 'model',
    bindings: {}
  };

  BindingsInstance = {
    getModel: function() {
      return this[this.constructor.model];
    },
    setModel: function(model) {
      return this[this.constructor.model] = model;
    },
    walkBindings: function(fn) {
      var field, selector, _ref, _results;
      _ref = this.constructor.bindings;
      _results = [];
      for (selector in _ref) {
        field = _ref[selector];
        _results.push(fn(selector, field));
      }
      return _results;
    },
    applyBindings: function() {
      var _this = this;
      return this.walkBindings(function(selector, field) {
        _this._bindModelToEl(_this.getModel(), field, selector);
        return _this._bindElToModel(_this.getModel(), field, selector);
      });
    },
    _forceModelBindings: function(model) {
      var _this = this;
      return this.walkBindings(function(selector, field) {
        return _this.$(selector).val(model[field]);
      });
    },
    changeBindingSource: function(model) {
      var _this = this;
      this.getModel().unbind('change');
      this.walkBindings(function(selector) {
        return _this.el.off('change', selector);
      });
      this.setModel(model);
      this._forceModelBindings(model);
      return this.applyBindings();
    },
    _bindModelToEl: function(model, field, selector) {
      return this.el.on('change', selector, function() {
        return model[field] = $(this).val();
      });
    },
    _bindElToModel: function(model, field, selector) {
      var _this = this;
      return model.bind('change', function() {
        return _this.$(selector).val(model[field]);
      });
    }
  };

  Spine.Controller.extend(BindingsClass);

  Spine.Controller.include(BindingsInstance);

}).call(this);
